### ISSUE TITLE
Versión OpenCV

### ISSUE THREAD

**Issue by JorgePerC** [Manchester-Robotics/ROSApril2022_Students#1]
Holaaa, buenas tardes, tengo una pregunta rápida

Vamos a utilizar una versión específica de OpenCV? Es para descargarlo en la computadora y que la transición de Laptop-Jetson sea más sencilla. 
También tengo la pregunta de si ¿hay preferencia entre usar la de Python o la de C++?

Graciaas :D

**Comment by MarcFacerias** [comment]
Respecto al lenguaje, el curso está diseñado con python en mente, por lo que nuestra recomendación es usarlo. Respecto a la versión de OpenCv estamos usando la 4.1.1 en la jetson
