### ISSUE TITLE
Problema para usar la camara con  roslaunch ros_deep_learning video_viewer.ros1.launch

### ISSUE THREAD

**Issue by Noemi1313** [Manchester-Robotics/ROSApril2022_Students#10]
Tenemos un problema para activar la camara con el nodo de roslaunch ros_deep_learning video_viewer.ros1.launch mediante ssh. Estos son los mensajes de error que nos aparecen:
![Captura de pantalla de 2022-04-28 15-03-25](https://user-images.githubusercontent.com/51099544/165836526-203be4b7-6ca2-4cbc-9e32-1f1404d88eb7.png)
![Captura de pantalla de 2022-04-28 15-03-20](https://user-images.githubusercontent.com/51099544/165836536-4b6abca4-0adb-44f4-8854-d218a0f10dff.png)

**Comment by rebecavelasco** [comment]
Hola, Noemi:

Como lo platicamos, vamos a revisar ambas extremos de la conexion del cable de la camara. Si el problema continua, trata de usar un cable diferente ( especialmente porque dices que se ve doblado). Si el problema continua prueba otra camara ( si puedes pedir una a un companero, y/0 prueba tu camara en otra puzzlebot. 

Esto nos podra ayudar en que punto puede estar el problema. Si no se corrige, escrubenos los resultados de estas pruebas y podemos proceder diferente dependiendo de que nos indiquen.

Saludos.

Rebeca

**Comment by Noemi1313** [comment]
Hola,

Probamos la cámara en otro puzzlebot y funcionó sin problemas, pero al conectar otra cámara en nuestra Jetson, nos arroja el mismo error. No creemos que sea un problema del flasheo porque sí encuentra el paquete.

**Comment by rebecavelasco** [comment]
Hola. Noemi:

Primero, te refieres a la camera y el cable, cuando te hablas de probar la camara o solo la camara? Si solo fue la camara, prueba otro cable, por favor. 

Segundo, si despues de probar la camara con otro cable en tu jetson, los pasos que seguirian si van en rumbo de probar la imagen de la SD de tu jetson, por que? Apesar de que este error puede ser fisico, tambien puede ser tambien un problema de configuracion del repositorio de NVIDIA, que puede deberse a un update, o en tal vez incluso a algun archivo corrupto o un performance raro de la SD. 

Te recomiendo hacer lo siguiente: 

- Primero vamos a hacerle un update. Conecta el robot a internet ( puedes hacer esto con cable ethernet), Abre una terminal y usa los siguiente instrucciones :

>                               To update to a new point release
> Enter the command:
> 
> $ sudo apt update
> apt reads a list of packages from the remote APT repository and identifies new and upgradable packages.
> 
> Enter the command:
> 
> $ apt list --upgradable
> apt displays a list of new and upgradable packages.
> 
> To install the basic packages for Jetson Linux, enter the command:
> 
> $ sudo apt upgrade
> Reboot your Jetson device when the upgrade is finished.

- Si esto no funciona, intenta con un nueva SD con una imagen del Puzzlebot, haz el update del paso anterior y prueba nuevamente. 

Saludos, 

Rebeca

**Comment by Noemi1313** [comment]
Hola Rebeca, 

Ya pudimos resolver el problema sin cambiar nada de la parte de hardware. Utilizamos el comando: 
$ unset DISPLAY

Muchas gracias.
