### ISSUE TITLE
Image message

### ISSUE THREAD

**Issue by JorgePerC** [Manchester-Robotics/ROSApril2022_Students#11]
Hola, buenas tardes :)

Estaba asimilando el código de ejemplo del [bridge](http://wiki.ros.org/cv_bridge/Tutorials/ConvertingBetweenROSImagesAndOpenCVImagesPython). 

Me surgió una pregunta: ¿hay manera de publicar en un tópico de ros un mensaje de tipo "imagen Opencv"? (Sé que a bajo nivel es un numpy array)

La cuestión reside en que si tenemos un capturer de OpenCV, pues ténicamente ya no necesitamos el bridge para convertir la variable de la imagen a algo manipulable en OpenCV. Un caso similar, queremos que nuestro proceso de extracción de información por OpenCV, esté divido en nodos. Ej. (seccionBlur -> seccionThreshold -> seccionIdentificacionBlob). ¿Estamos forzados a convertir con el bridge entre los formatos de Image y los compatibles con OpenCV para comunicar nodos de procesamiento de imgs? 

¿hay alguna ventaja de usar Image al compartir imágenes entre nodos?

Gracias, salu2

**Comment by MarcFacerias** [comment]
Lo standard es usar cv_bridge pero debería ser possible hacer un tipo de mensaje personalizado para que no sea necesario. En todo caso la mayoría de librerías utilizan el standard de ROS.
