### ISSUE TITLE
Simulación puzzlebot con pista (lineas neagras sobre fondo claro)

### ISSUE THREAD

**Issue by artur84** [Manchester-Robotics/ROSApril2022_Students#13]
Hola equipo de Manchester Robotics, ¿tendrán alguna simulación para el puzzlebot con una pista que tenga líneas negras sobre fondo claro? En caso de que la tengan , sería super útil que nos la compartieran para probar la actividad de esta semana en simulación. 
Saludos y Muchas gracias.

**Comment by MarcFacerias** [comment]
Lo puedes encontrar en la carpeta extra files de este mismo git.
