### ISSUE TITLE
matplotlib interfaz ROS

### ISSUE THREAD

**Issue by felipeflourwears** [Manchester-Robotics/ROSApril2022_Students#14]
¡Hola! ¿Qué tal? Teníamos una duda para realizar el histograma  de la pasada sesión del jueves, donde teníamos que sacar la información relevante de la suma de columnas de una imagen, el principal problema es el interfaz con ROS y matplotlib, y es un problema hacer las gráficas.

**Comment by MarcFacerias** [comment]
Hola, podrias ser un poco mas concreto ? Que funcion te da problemas?

**Comment by MarcFacerias** [comment]
Me alegro! Tened en cuenta que podéis instalar cualquier package en la jetson de la misma forma que en vuestro ordenador.
