### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by AlDomL9** [Manchester-Robotics/ROSApril2022_Students#15]
Good evening,
We have developed some code for this afternoon's activity and would like to test it. However, upon running the code, it becomes clear to us that we are missing some files. For starters the directory called 'myData' (and whichever files it should contain), and secondly a CSV file called 'labels.csv'. 
We would like to know where we can get such files, or if we should create them and if so, what structure should they have and what data, specifically, must they contain. 
Thank you in advance for your assistance. We are eager to hear from you.

**Comment by MarcFacerias** [comment]
You should be able to find both files in the database link that we gave to you. In any case, I'll share a link with you tonight so that you can download them. https://www.dropbox.com/s/2fut3wweg4g72y1/Data.zip?dl=0
