### ISSUE TITLE
Training Issues

### ISSUE THREAD

**Issue by AlDomL9** [Manchester-Robotics/ROSApril2022_Students#16]
Greetings,
We are testing our code and we have come across an error. We have modified the code you have kindly given to us to accommodate for only 5 classes (14, 32, 33, 35, 40). We believe the error surely comes from our modifications though we do not know how to solve it and we have found no help online. 
We attach a screenshot of the error and our code hoping you can check it and guide us towards the solution of this issue.
Thank you ever so much for your help.
Error: (https://user-images.githubusercontent.com/58440560/170578536-b60912fb-67ed-467e-99b3-4afd4d262a2d.png)
Code: (https://github.com/Manchester-Robotics/ROSApril2022_Students/files/8782068/Train_Template.zip)

**Comment by A01379375** [comment]
UPDATE: We have now been able to test it with the full MyData dataset and used the original code, and still got the same error afore mentioned.

**Comment by A01379375** [comment]
We've also noticed this warning (I think) in the imports: 
![image](https://user-images.githubusercontent.com/73500149/170601612-e68b2caa-fa65-4879-9857-2537a71f9d11.png)

**Comment by MarcFacerias** [comment]
Hello, sorry for the delayed response you'll have to take into account the following points to solve your issue: 

1. You need to specify the activation function of the layers you have. 
2. You'll need to format your data so it matches the input of the network, in this case (N, 32, 32, 1)
3. You'll need to format the labels of your data to match the output of the network, you can do that with the function tf.one_hot

After solving this issues I was able to train the network properly, if you have problems with any of them let me know this afternoon and we can go through them.
