### ISSUE TITLE
Modificación de las luces del semáforo.

### ISSUE THREAD

**Issue by DannyAvilaL** [Manchester-Robotics/ROSApril2022_Students#18]
Hola,

Intenté realizar la modificación del color de los semáforos de acuerdo con el README en la línea:

```xml
<!-- EDIT ME FOR CHANGING COLOR--> 
<name>Gazebo/Green</name>
```

Sin embargo, al momento de guardar la modificación y volver a ejecutar la instrucción de roslaunch en la terminal, los semáforos permanecen igual.

¿Hay alguna otra línea dentro de los archivos indicados que se deba modificar?

**Comment by rebecavelasco** [comment]
Hola, Danny. 

Perdon por la tardanza. La razon por la que hace eso es por que el semaforo, esta precargado. Hay que volverlo a cargar, insertando el modelo. Hare nos cambios en el Readme para que sea mas entedible. Una disculpa por la tardanza.

**Comment by rebecavelasco** [comment]
Subi el archivo con el plugin para que ya no tengan que cambiar el semaforo manualmente. Ojala les ayude.
