### ISSUE TITLE
Waiting for suscriber to connect to /cmd_vel

### ISSUE THREAD

**Issue by MarcosEduardoGarcia** [Manchester-Robotics/ROSApril2022_Students#3]
Al intentar teleoperar el robot desde mi computadora me aparece el mensaje de Waiting for suscriber to connect to /cmd_vel  funciona en otras computadoras la teleoperacion excepto en la mia por favor diganme que hacer espero su respuesta

**Comment by rebecavelasco** [comment]
Hola, Marcos: 

Perdon que no vi tu issue. Aun sigues con este problema? Me puede sonar que hay un problema de comunicacion, pero necesitaria mas detalles.

Imagino que estas connectandote a la red inalambrica del Puzzlebot y mandas la info de tu computadora? Estas en maquina virtual? Describeme un poco como estan las conexiones con tu compu y el puzzlebot, sistema operativo, y como corres ROS.

**Comment by MarcosEduardoGarcia** [comment]
Somos equipos de 3 y reallizando los comandos de export y donde ingresamos la ip y todo eso funciona muy bien en las compus de mis compañeros pueden enviar y teleoperar el robot sin embargo solo en mi laptop no funciona se queda marcando ese error de waiting for suscriber Marc y Mario mencionaron algo de firewall y otras cosas que dijeron iban a responder aqui en el issue por lo que aun sigo batallando con eso lo unico que puedo hacer es un rostopic list pero de ahi en fuera siempre marca lo mismo al intentar teleoperar el robot

**Comment by MarcFacerias** [comment]
Revisamos el tema de firewall y no debería de dar problemas. Revisa que el ROS URI y el ROS IP este bien configurado cada vez que abras un terminal. También revisa que una vez dentro de esa red puedas comunicarte con la jetson (ja sea haciendo un ping o un ssh). Si no lo consigues ponte en contacto con alguien del equipo durante la sesión y lo revisamos.
