### ISSUE TITLE
My Jetson is not powering up

### ISSUE THREAD

**Issue by AlanMR20** [Manchester-Robotics/ROSApril2022_Students#4]
I connected the black cable for the controller to a USB port of the Jetson while it was powered, and after that the Jetson haven't turn un again :( .

**Comment by rebecavelasco** [comment]
Sorry, Alan. We missed your issue. My apologies. Luckily we had the chance to chat about it in today's lecture. Please don't forget the following steps for the troubleshooting: 

Only powering the Jetson nano with a new SD ( with the provided Puzzlebot image, of course), a different cable and using a 3A power source. If it doesn't work, please add to this issue the status of the LED lights in the jetson, and any other info you find relevant. 

If it works, double-check your connections before reconnecting the hackerboard to the Jetson. Remember to check the slider for the power supply, you can find that info in the manual.
