### ISSUE TITLE
No se actualizan los topicos /wl y /wr en codigo python

### ISSUE THREAD

**Issue by Franco-A01733927** [Manchester-Robotics/ROSApril2022_Students#5]
Al ejecutar nuestro código, obtenemos lo siguiente:

![Screenshot from 2022-04-21 16-10-47](https://user-images.githubusercontent.com/67660198/164552980-d8420c8e-1ae5-4973-b12c-09444bf5bea7.png)

![Screenshot from 2022-04-21 16-16-31](https://user-images.githubusercontent.com/67660198/164553755-bddb9039-98fb-4174-ab68-cbeeaf832f69.png)

Donde se puede notar que si se está publicando el tópico, verificado por el comando echo, por otro lado está ejecutándose el Teleop, el cual se encarga de mover las llantas, pero al correr el código no se actualiza correctamente, solamente en contadas ocasiones lee algo, ignorando en ocasiones la lectura de /wl o de /wr, de manera intercalada.

Si nos pudieran ayudar con la revisión del código adjunto a continuación, nos seria de mucha ayuda, igualmente cualquier consejo u observación es bienvenido.

[Controller.zip](https://github.com/Manchester-Robotics/ROSApril2022_Students/files/8535014/Controller.zip)

**Comment by MarcFacerias** [comment]
En un primer vistazo diría que el error esta en la función "get_vel" ya que cada vez que la llamas creas un nuevo init_node y una nueva instancia de la clase que desaparece al salir de la función. Mi recomendación es que programes la función de get_vel dentro de la clase "mi_robot" y crees solo una instancia de esa clase. Te dejo una muestra de la estructura a la que me refiero

```
class robot()

    def init:
        self.node = ...
        self.sub1 = ...
        etc

    def callback1
        ...
    def callback2
        ...
    def get_values
        return wl,wr

def main:

    robot = robot()
    
    while (...): 
        robot.get_values()

```
