### ISSUE TITLE
La tarjeta Jetson se apaga al aumentar la velocidad de los motores

### ISSUE THREAD

**Issue by Franco-A01733927** [Manchester-Robotics/ROSApril2022_Students#6]
Al momento de ejecutar el Teleop y subir la velocidad a más de 0.4, la Jetson se apaga, pero la Hackerboard sigue encendida y los motores moviéndose, por lo que es necesario apagar la batería y volver a prender todo.

Se esta usando una bateria de 10000 mah, con dos salidas de 18w de 5V/3A, un cable va de la bateria directamente a la entrada tipo-c de la jetson y el segundo de la bateria a la hackerboard, usando el puerto color verde que requiere del cable pelado color negro que venia con el puzzlebot.

Cómo nota nuestra hackerboard, dispone de solo dos switches, uno para prender y apagar la hackerboard y un segundo para encender y apagar motores.

**Comment by MarcFacerias** [comment]
A priori parece que las conexiones estan bien, yo te recomendaria probar de poner los motores al maximo solo usando la board para testear que esa parte funciona y probar con otra bateria por si acaso.

**Comment by Franco-A01733927** [comment]
Si, de hecho ya lo habíamos revisado con Rebeca, y nos comentó que abriéramos un issue, porque por si solos los motores funcionan correctamente solo con la hackerboard, pero al conectar la jason, toma el poder del puerto USB de la jason y se limita a lo que puede entregar el puerto y no los 3A de la batería, bueno al menos esa es nuestra hipótesis.

**Comment by christopher-blum** [comment]
Hello! I would suggest trying with two separate batteries for now, and see what the results of that testing are. Then, bring up the issue to the teachers during your session today, and it can be solved.
