### ISSUE TITLE
Problema para ejecutar video_source.ros1.launch

### ISSUE THREAD

**Issue by Franco-A01733927** [Manchester-Robotics/ROSApril2022_Students#8]
Me aparece el siguiente error al ejecutar el archivo video_source.ros1.launch

```
/home/puzzlebot/catkin_ws/src/ros-deep-learning/launch/video_source.ros1.launch: line 1: syntax error near unexpected token `newline'
/home/puzzlebot/catkin_ws/src/ros-deep-learning/launch/video_source.ros1.launch: line 1: `<launch>'

```

 Pasos que seguí para ejecutar el archivo:
1. Hacer SSH al puzzlebot
2. Ir al directorio de catkin_ws
3. Hacer source
4. Ejecutar “rosrun ros_deep_learning video_source.ros1.launch”

**Comment by MarcFacerias** [comment]
Este comando "rosrun ros_deep_learning video_source.ros1.launch"  deberia ser "roslaunch ros_deep_learning video_source.ros1.launch" ya que es un launch file
